theme: null
title: mac-onboarding
description: Privacy-first macOS configuration bootstrapper for MDM-managed Macs
url: "https://oleg-koval.github.io/mac-onboarding"
author: Oleg Koval
author_url: "https://olegkoval.com"
github_url: "https://github.com/oleg-koval/mac-onboarding"
